model:
  src_vocab_size: 4
  tgt_vocab_size: 4
  d_model: 128
  num_heads: 4
  d_ff: 256
  num_encoder_layers: 3
  num_decoder_layers: 3
  max_len: 128
  dropout: 0.1
  architecture: 'encoder_decoder'
  is_sinusoidal: false

training:
  batch_size: 32
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0

data:
  dataset_path: 'path/to/dataset'
  eval_size: 10000

device:
  use_cuda: true